### ISSUE TITLE
Fix dependencies vulnerabilities

### ISSUE THREAD

**Issue by sergeyvolkov** [pagerinc/minion#29]
Have 3 vulnerabilities from Github Security alerts: https://github.com/pagerinc/minion/network/alerts and 89 vulnerabilities from npm audit:
```
found 89 vulnerabilities (1 low, 85 moderate, 3 high) in 2016 scanned packages
  run `npm audit fix` to fix 13 of them.
  76 vulnerabilities require semver-major dependency updates.
```

**Comment by cilindrox** [comment]
@pagerinc/backend need someone to take a look at this

**Comment by jvelezpo** [comment]
@cilindrox  I think we can close this, i just forked, pull, and ran npm i and this is the output

```
➜  minion git:(master) npm i
audited 1493 packages in 2.491s
found 0 vulnerabilities
```
